[ Plinio Moraes ] - Exercicio 01 - Done
plinioSMoraes/Bootcamp-Orion pull request #2
Opened 2023-10-09 16:14 UTC by plinioSMoraes

2023-10-09 18:18 UTC, plinioSMoraes commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Plinio Moraes] Exercicio 01](https://trello.com/c/83PEVy3s/75-plinio-moraes-exercicio-01)

2023-10-10 12:58 UTC, aLiviaMs requested changes

2023-10-10 12:58 UTC, aLiviaMs commented on exerciseFunction.js
> +const totalVogalsInString = (string) => {
Precisamos do arquivo ts, para avaliar.

2023-10-10 12:59 UTC, aLiviaMs commented
O PR também deve ser redirecionado a branch `develop`. 
Neste caso o PR está sendo direcionado para a branch `main`

2023-10-10 15:36 UTC, plinioSMoraes commented on exerciseFunction.js
> +const totalVogalsInString = (string) => {
Ok

2023-10-10 16:16 UTC, plinioSMoraes commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Plinio Moraes] Exercicio 01](https://trello.com/c/83PEVy3s/75-plinio-moraes-exercicio-01)

2023-10-11 13:53 UTC, aLiviaMs commented
Você consegue mudar a branch de `main` para `develop` aqui mesmo, irei fazer isso e fechar os outros PRs só para manter o padrão, pois já fiz comentários por aqui.

2023-10-11 14:12 UTC, aLiviaMs requested changes

2023-10-11 14:12 UTC, aLiviaMs commented on exerciseFunction.ts
> +const totalVogalsInString = (string: string): {
totalVowelsInString**

Vogais em inglês o correto é Vowels

2023-10-11 14:12 UTC, aLiviaMs commented on exerciseFunction.ts
> +    const map: { [key: string]: number} = {
A função não está levando em conta as vogais acentuadas, por exemplo, se eu escrever: São Paulo

```
  "vowelsCount": {
    "a": 1,
    "e": 0,
    "i": 0,
    "o": 2,
    "u": 1
  },
```

Percebe que apenas um 'a' foi contabilizado?

Recomendo que utilize [Expressões Regulares(regex)](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Regular_Expressions) pra criar uma menor complexidade do seu código.
Pode manter o vowelsCount dessa forma se quiser, desde que ele contabilize as vogais acentuadas tbm.

2023-10-11 21:15 UTC, aLiviaMs requested changes

2023-10-11 21:15 UTC, aLiviaMs commented on exerciseFunction.ts
> +var countVowels = function (string: string) {
Evite a utilização de `var`.

Motivo principal: a falta de tipagem estática, `var` não fornece tipagem estática, o que significa que as variáveis declaradas com `var` não têm um tipo definido explicitamente. Isso pode levar a bugs difíceis de rastrear, pois o TypeScript não pode detectar erros de tipo em tempo de compilação.

Em vez de `var`, o TypeScript oferece outras palavras-chave para declarar variáveis, como `let` e `const`, que são mais seguras e têm escopo de bloco.

```
const countVowels = (word: string): string => {
 // Código aqui
}
```

2023-10-11 21:15 UTC, aLiviaMs commented on exerciseFunction.ts
> +var countVowels = function (string: string) {
Não esqueça de tipar o retorno das funções também, é importante.

2023-10-11 21:15 UTC, aLiviaMs commented on exerciseFunction.ts
> +var countVowels = function (string: string) {
É uma má prática nomear parâmetros de função com o mesmo nome do tipo porque isso pode levar a confusão e a problemas de legibilidade no código, tente sempre declarar não só seus parâmetros mas como váriaveis de uma forma que a legibilidade não seja um problema (isso facilita pessoas que possam fazer manutenções no seu código posteriormente e as próprias pessoas que estão revisando seu PR).

Sugestão de leitura sobre: [Clean Code](https://github.com/ryanmcdermott/clean-code-javascript)

2023-10-11 21:15 UTC, aLiviaMs commented on exerciseFunction.ts
> +    var vowelsCount = {};
Muitos `var` no algoritmo, renomeie para `const` ou `let`, levando seus escopos em conta.

`const` para valores que são **imutáveis**.
`let` para valores que são **mutáveis**

2023-10-11 21:15 UTC, aLiviaMs commented on exerciseFunction.ts
> +    var vowelsCount = {};
Faltou tipar algumas váriaveis, é importante que todas estejam tipadas.

Incluindo as que são htmls.
Como este:

`const card: HTMLElement | null = document.getElementById('cardContainer');
`

2023-10-11 22:53 UTC, aLiviaMs requested changes

2023-10-11 22:53 UTC, aLiviaMs commented on exerciseFunction.ts
> +const totalVowelsInString = (string: string): {
Esqueceu de alterar o nome aqui ainda referente ao comentrário sobre má prática de nomear parâmetros de função com o mesmo nome do tipo

2023-10-13 15:05 UTC, aLiviaMs approved these changes

2023-10-13 15:06 UTC, merged