[ Plinio Moraes ] - Exercicio 02 - Done
plinioSMoraes/Bootcamp-Orion pull request #3
Opened 2023-10-09 18:16 UTC by plinioSMoraes

2023-10-09 18:18 UTC, plinioSMoraes commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Plinio Moraes] Exercicio 02](https://trello.com/c/tcd9IjKW/74-plinio-moraes-exercicio-02)

2023-10-10 13:07 UTC, aLiviaMs commented
O PR também deve ser redirecionado a branch `develop`. 
Neste caso o PR está sendo direcionado para a branch `main`

2023-10-10 13:50 UTC, aLiviaMs requested changes

2023-10-10 13:50 UTC, aLiviaMs commented on script.ts
> +// e) Demonstre todas as funções com o paradigma funcional e com o imperativo
É necessário mostrar em ambos os paradigmas, não apenas no funcional.

Sugestão: renomear as funções neste estilo:

`getNameByIdFunctional();`
`getNameByIdImperative();`

2023-10-10 19:25 UTC, plinioSMoraes commented on script.ts
> +// e) Demonstre todas as funções com o paradigma funcional e com o imperativo
Eu separei em dois arquivos as funções

2023-10-11 14:35 UTC, aLiviaMs approved these changes

2023-10-11 14:35 UTC, aLiviaMs commented on database.ts
> +interface IUser {
muito bom a criação de interface para isso!

2023-10-11 14:35 UTC, merged