[ Plinio Moraes ] - Feature: Exercicio 3 - Feito
plinioSMoraes/Bootcamp-Orion pull request #6
Opened 2023-10-13 23:00 UTC by plinioSMoraes

2023-10-13 23:15 UTC, plinioSMoraes commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Plinio Moraes] Exercicio 03](https://trello.com/c/pDm1sCVJ/76-plinio-moraes-exercicio-03)

2023-10-14 00:52 UTC, ewelyn-samaris commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Ewelyn Samaris]Ex2](https://trello.com/c/KYlnx6Gc/53-ewelyn-samarisex2)

2023-10-14 02:00 UTC, aLiviaMs approved these changes

2023-10-14 02:01 UTC, aLiviaMs requested changes
Sua branch está com conflitos, n é possível mergear

2023-10-14 09:49 UTC, aLiviaMs approved these changes

2023-10-14 09:49 UTC, merged